/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CliqueRouteImport } from './routes/clique'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaNRouteImport } from './routes/pa.$n'

const CliqueRoute = CliqueRouteImport.update({
  id: '/clique',
  path: '/clique',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaNRoute = PaNRouteImport.update({
  id: '/pa/$n',
  path: '/pa/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/clique': typeof CliqueRoute
  '/pa/$n': typeof PaNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/clique': typeof CliqueRoute
  '/pa/$n': typeof PaNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/clique': typeof CliqueRoute
  '/pa/$n': typeof PaNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assignments' | '/clique' | '/pa/$n'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assignments' | '/clique' | '/pa/$n'
  id: '__root__' | '/' | '/assignments' | '/clique' | '/pa/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CliqueRoute: typeof CliqueRoute
  PaNRoute: typeof PaNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clique': {
      id: '/clique'
      path: '/clique'
      fullPath: '/clique'
      preLoaderRoute: typeof CliqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pa/$n': {
      id: '/pa/$n'
      path: '/pa/$n'
      fullPath: '/pa/$n'
      preLoaderRoute: typeof PaNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  CliqueRoute: CliqueRoute,
  PaNRoute: PaNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
